// Tipos de acciones auditables propuestas
export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SALE_CREATE: 'SALE_CREATE',
  SALE_CANCEL: 'SALE_CANCEL',
  SALE_FULFILL: 'SALE_FULFILL',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE_ROLE: 'USER_UPDATE_ROLE',
  USER_PASSWORD_CHANGE: 'USER_PASSWORD_CHANGE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  PRINT_INVOICE: 'PRINT_INVOICE',
  PRINT_KITCHEN: 'PRINT_KITCHEN',
  SYNC_PUSH: 'SYNC_PUSH',
  SYNC_PULL: 'SYNC_PULL'
};