export const BASE_PERMISSIONS = [
  'PRODUCT_VIEW','PRODUCT_CREATE','PRODUCT_EDIT','PRODUCT_DELETE',
  'SALE_CREATE','SALE_VIEW','SALE_CANCEL','SALE_FULFILL',
  'INVOICE_PRINT','KITCHEN_PRINT',
  'USER_VIEW','USER_CREATE','USER_EDIT','USER_PASSWORD_RESET',
  'ROLE_VIEW','ROLE_EDIT',
  'REPORT_VIEW','SYNC_RUN','AUDIT_VIEW',
  'CUSTOMER_VIEW','CUSTOMER_EDIT',
  'TAX_VIEW','TAX_EDIT',
  'SUPPLIER_VIEW','SUPPLIER_EDIT',
  'PURCHASE_VIEW','PURCHASE_CREATE',
  'INVENTORY_VIEW','INVENTORY_ADJUST',
  'ANALYTICS_VIEW','TIP_CONFIG','COST_VIEW'
];