// Definición de Roles y Permisos del dominio (puerto conceptual)
export const PERMISSIONS = {
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  SALE_CREATE: 'SALE_CREATE',
  SALE_VIEW: 'SALE_VIEW',
  SALE_CANCEL: 'SALE_CANCEL',
  INVOICE_PRINT: 'INVOICE_PRINT'
};

export const ROLES = {
  ADMIN: 'ADMIN',
  CAJERO: 'CAJERO',
  SUPERVISOR: 'SUPERVISOR',
  VISOR: 'VISOR'
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.CAJERO]: [
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.INVOICE_PRINT
  ],
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.SALE_VIEW,
    PERMISSIONS.SALE_CANCEL,
    PERMISSIONS.INVOICE_PRINT
  ],
  [ROLES.VISOR]: [
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.SALE_VIEW
  ]
};